// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	basic_feed "tiktok_demo/biz/router/basic/feed"
	basic_publish "tiktok_demo/biz/router/basic/publish"
	basic_user "tiktok_demo/biz/router/basic/user"
	interact_comment "tiktok_demo/biz/router/interact/comment"
	interact_favorite "tiktok_demo/biz/router/interact/favorite"
	social_message "tiktok_demo/biz/router/social/message"
	social_relation "tiktok_demo/biz/router/social/relation"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	social_relation.Register(r)

	basic_publish.Register(r)

	social_message.Register(r)

	interact_favorite.Register(r)

	basic_feed.Register(r)

	interact_comment.Register(r)

	basic_user.Register(r)

}
